# Site settings
title: 小院子 博客 
header-img: img/home-bg.jpg
email: liuhongqiang@live.cn
description: "Smallyard 博客。 @小小已然 | @smallyard | @小院子 "
baseurl: ""
url: "http://smallyard.cn"
#twitter_username: smallyard
github_username:  smallyard
#facebook_username:  smallyard
weibo_username: 232212306
zhihu_username: smallyard

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM

timezone: Asia/Shanghai
